### ISSUE TITLE
crashed by a leakage in the protection against non thread-safe ncurses

### ISSUE THREAD

**Issue by pfliu** [intel/numatop#91] opened 2024-10-31 02:10 UTC
Our test witnesses crash in numatop. The dump stack shows the crash happens in the ncurses. But after talking with ncurse guy, he tend to consider this is a race issue.

The race scenario looks like:
cons_handler()->getch()
and 
disp_handler() ->page_next_execute() -> ... -> wnoutrefresh()

Now two threads call into the ncurse library, which is not thread-safe.

Dos all calling to ncurse library originate from disp_handler() and cons_handler()? Can an additional mutex be introduced to protect the above scenario? 

Thanks,

Pingfan

**Comment by ak-intel** [comment] 2024-11-18 16:00
The problem is that the display thread wants to wait both for a pthread condition variable that is fed by multiple threads and the input file descriptor for key presses. So it was separated into two threads, one that does the initialization and the getch, and another that only waits for the condition variable with its input queue and then does all the output.

I think there is also a race with exit, reg_curses_fini is not synchronized with the display thread either.

For getch we can just move it into the disp_thread triggered by the cons thread. Same with the exit. And then move the initialization too, then everything curses is in the display thread.

Can you see if this patch fixes your problems?
[numactl-curses.txt](https://github.com/user-attachments/files/17803151/numactl-curses.txt)

**Comment by ak-intel** [comment] 2024-11-18 20:07
The latest pushed version fixes another race in my first version.

**Comment by pfliu** [comment] 2024-11-19 12:57
@ak-intel, thank you for the insight.
Since I can not reproduce it on my machine,  I ask my colleague who has a compute farm to reproduce it.
It may take several days before the crash occurs.

**Comment by ak-intel** [comment] 2024-11-19 20:41
The extra race is now fixed too.

**Closed** 2024-11-20 21:17 UTC

**Comment by pfliu** [comment] 2024-11-26 01:23
@ak-intel, Using your last patch, the crash can not be reproduced in the compute farm any longer.

Thanks a lot
